service: campsite-styled-text-tokdio
image: truemarkdev/campsite-styled-text
secrets_path: .kamal/campsite-secrets

servers:
  web:
    - 192.168.10.7

proxy:
  ssl: false
  hosts:
    - camp-styled-text.tokdio.com
    - styled-text.camp.home
  app_port: 9000
  healthcheck:
    path: /up
    interval: 10

registry:
  server: localhost:5555

builder:
  arch: amd64
  remote: ssh://prakash@builder.home
  context: .
  dockerfile: apps/styled-text-server/Dockerfile

env:
  clear:
    NODE_ENV: production
    PORT: "9000"
  secret:
    - AUTHTOKEN

ssh:
  user: debian
