service: campsite-sync-server

image: truemarkdev/campsite
secrets_path: apps/sync-server/.env.local

servers:
  web:
    - 51.91.240.88

proxy:
  ssl: true
  hosts:
    - camp-sync.polo-apps.com
  app_port: 9000

registry:
  server: localhost:5555

env:
  secret:
    - API_BASE_URL
    - SENTRY_DSN

builder:
  arch: amd64
  context: .
  dockerfile: apps/sync-server/Dockerfile

ssh:
  user: deploy
