service: campsite-web-public-staging
image: truemarkdev/campsite-web
secrets_path: .kamal/campsite-secrets

servers:
  web:
    - 192.168.10.7

proxy:
  ssl: false
  host: camp.tokdio.com
  app_port: 3000
  healthcheck:
    path: /robots.txt
    interval: 10

registry:
  server: localhost:5555

builder:
  arch: amd64
  remote: ssh://prakash@builder.home
  context: .
  dockerfile: apps/web/Dockerfile
  args:
    NEXT_PUBLIC_WEB_URL: https://camp.tokdio.com
    NEXT_PUBLIC_SITE_URL: https://camp.tokdio.com
    NEXT_PUBLIC_SYNC_URL: wss://camp-sync.tokdio.com
    NEXT_PUBLIC_API_URL: https://camp-api.tokdio.com
    NEXT_PUBLIC_AUTH_URL: https://camp-auth.tokdio.com
    NEXT_PUBLIC_ADMIN_URL: https://camp-admin.tokdio.com
    NEXT_PUBLIC_CDN_URL: https://camp-cdn.tokdio.com
    NEXT_PUBLIC_IMGIX_URL: https://camp-cdn.tokdio.com
    NEXT_PUBLIC_OBJECT_STORAGE_URL: https://camp-objects.tokdio.com
    NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA: <%= `git rev-parse HEAD`.strip %>
env:
  clear:
    NODE_ENV: production
    PORT: "3000"
  secret:
    - REVALIDATE_STATIC_CACHE_TOKEN

ssh:
  user: debian
